#pragma once

// ============================================================================
// SymbolTableBuilder.h — Pass 1: Build the scope tree and all symbols
//
// Two-phase pass:
//   1a: Walk all modules/declarations, create symbols, build scope tree,
//       set astScopeNode on every node, set ParameterNode::resolvedSymbol,
//       auto-generate ctor/dtor, build vtables.
//   1b: Resolve import declarations (after all module scopes exist).
//
// V2 improvements over V1:
//   - Sets astScopeNode directly (no childIndexStack_)
//   - Sets ParameterNode::resolvedSymbol (eliminates scanForParamSymbols)
//   - Uses SymbolTable::pushScope/popScope with scope stack
//   - TypeSymbol IS the type (no separate TypeRegistry)
// ============================================================================

#include "mingus/AstNode.h"
#include "mingus/Expressions.h"
#include "mingus/Statements.h"
#include "mingus/Declarations.h"
#include "mingus/Symbols.h"
#include "mingus/SymbolTable.h"
#include "mingus/sema/ErrorReporter.h"

namespace mingus {

class SymbolTableBuilder : public ASTVisitor {
public:
    SymbolTableBuilder(SymbolTable& symbolTable, ErrorReporter& errors);

    // Entry point: builds the entire scope tree
    void build(ProgramNode& program);

    // ---- Visitor overrides ----
    void visit(ProgramNode& node) override;
    void visit(ModuleNode& node) override;
    void visit(BlockStatementNode& node) override;

    // Declarations
    void visit(VariableDeclaration& node) override;
    void visit(TupleDestructuringDeclaration& node) override;
    void visit(FunctionDeclaration& node) override;
    void visit(ConstructorDeclaration& node) override;
    void visit(DestructorDeclaration& node) override;
    void visit(ExternFunctionDeclaration& node) override;
    void visit(OperatorDeclaration& node) override;
    void visit(EnumDeclaration& node) override;
    void visit(StructDeclaration& node) override;
    void visit(ClassDeclaration& node) override;
    void visit(InterfaceDeclaration& node) override;
    void visit(ImportDeclaration& node) override;
    void visit(TypedefDeclaration& node) override;

    // Statements (set scope, recurse)
    void visit(ExpressionStatement& node) override;
    void visit(ReturnStatement& node) override;
    void visit(IfStatement& node) override;
    void visit(ForStatement& node) override;
    void visit(WhileStatement& node) override;
    void visit(DoWhileStatement& node) override;
    void visit(LabeledStatement& node) override;
    void visit(BreakStatement& node) override;
    void visit(ContinueStatement& node) override;
    void visit(DeleteStatement& node) override;
    void visit(SwitchStatement& node) override;

    // Expressions (set scope, recurse for nested declarations/lambdas)
    void visit(IntegerLiteral& node) override;
    void visit(FloatLiteral& node) override;
    void visit(BoolLiteral& node) override;
    void visit(CharLiteral& node) override;
    void visit(StringLiteral& node) override;
    void visit(NullLiteral& node) override;
    void visit(InterpolatedStringExpression& node) override;
    void visit(IdentifierExpression& node) override;
    void visit(QualifiedNameExpression& node) override;
    void visit(ThisExpression& node) override;
    void visit(MemberAccessExpression& node) override;
    void visit(BinaryExpression& node) override;
    void visit(UnaryExpression& node) override;
    void visit(AssignmentExpression& node) override;
    void visit(TernaryExpression& node) override;
    void visit(IndexExpression& node) override;
    void visit(CallExpression& node) override;
    void visit(CastExpression& node) override;
    void visit(NewExpression& node) override;
    void visit(SizeOfExpression& node) override;
    void visit(TupleExpression& node) override;
    void visit(MatchExpression& node) override;
    void visit(PipeExpression& node) override;
    void visit(LambdaExpression& node) override;
    void visit(VariableDeclarationExpression& node) override;

private:
    SymbolTable& symbolTable_;
    ErrorReporter& errors_;

    // Scope helpers
    void setScope(AstBaseNode& node);
    void pushBlockScope(AstBaseNode& node);
    void visitStatements(std::vector<std::shared_ptr<StatementBaseNode>>& stmts);

    // Symbol creation helpers
    void createParameterSymbols(
        std::vector<std::shared_ptr<ParameterNode>>& params,
        const std::shared_ptr<FunctionSymbol>& funcSym);

    // Class/struct helpers
    void buildVtable(ClassSymbol* classSym);
    void autoGenerateConstructor(ClassDeclaration& node,
                                 const std::shared_ptr<ClassSymbol>& classSym);
    void autoGenerateDestructor(ClassDeclaration& node,
                                const std::shared_ptr<ClassSymbol>& classSym);

    // Import resolution (Phase 1b)
    void resolveAllImports(ProgramNode& program);

    // State tracking
    bool inTypeScope_ = false;   // true when inside struct/class members
    std::shared_ptr<ClassSymbol> currentClass_;  // for ctor/dtor context
};

} // namespace mingus
